### ISSUE TITLE
"incorrect access token" + "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by dc540** [nextcloud/integration_gitlab#37]
Connecting to internal gitlab for the first time. Nextcloud 23, latest integration_gitlab.

Everything has internal certs signed by an internal ca.

I generated a personal access token in gitlab, try to use it to connect to gitlab in my nextcloud/gitlab dashboard widget, and i get "incorrect access token."  Checking the nextcloud logs, I see corresponding log entries including:

"app":"integration_gitlab","method":PUT","url"/index.php/apps/integration_gitlab_config","message":"GitLab API error : cURL error 60: SSL certificate problem: unable to get local issuer certificate..."

Command line cURL API queries which include my personal access tokens complete successfully.

Any clues on where to look?

**Comment by gl-njanz** [comment]
Hi! 

You might have to get GitLab to trust your internal CA. On [Omnibus installations](https://docs.gitlab.com/omnibus/), you can to this by adding the signing CAs certificate (as PEM) to `/etc/gitlab/trusted-certs/` and running `gitlab-ctl reconfigure`.

More on that topic here: https://docs.gitlab.com/omnibus/settings/ssl.html#details-on-how-gitlab-and-ssl-work

That is, unless I read it incorrectly and Nextclouds PHP is having trust issues 😅

**Comment by dc540** [comment]
I should have provided a sanitized version of the complete error. The cert it's having trouble with is that of my gitlab server. So it seems the trust issue is on the nextcloud side.  On the gitlab side, my internal ca cert is already trusted. I added the cert for the nextcloud server as well and did a reconfigure, just to be thorough, but no change in behavior. 

I also tried adding the ca cert, on the nextcloud side, to the cert store at /etc/pki/nssdb. Restarted php-fpm for good measure.

**Comment by solsys** [comment]
Spent an evening fighting with this problem and partially figured it out.  Nextcloud ships with its own `ca-bundle.crt` file which lives in the `resources/config` directory.   For some reason, (at least on the linuxserver.io docker container) it uses this file for it's internal Guzzle wrapper rather than the system ca store: 

https://github.com/nextcloud/server/blob/d2d408bba763accf5873e2a3a0deb8629e0073ac/lib/private/Http/Client/Client.php#L124

Appending your ca cert to this file fixes the problem, but unsure if it will survive a nextcloud update.

Not enough of a nextcloud or docker expert to know if this is a bug in Nextcloud, or the container.

**Comment by dc540** [comment]
Perfect. That solved it for me. Thanks so much for your response!
